# Generated by Django 5.1.1 on 2024-11-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre de Empresa"),
                ),
                ("mission", models.TextField(verbose_name="Mision de Empresa")),
                ("vision", models.TextField(verbose_name="Vision de Empresa")),
                (
                    "general_manager",
                    models.CharField(max_length=100, verbose_name="Gerente General"),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=100, verbose_name="Ubicacion de Empresa"
                    ),
                ),
                ("fundation_date", models.DateField(verbose_name="Fecha de Fundacion")),
                ("ruc", models.CharField(max_length=11, verbose_name="Ruc de Empresa")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Telefono de Empresa"),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Correo de Empresa"),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Contraseña"
                    ),
                ),
            ],
        ),
    ]
