# Generated by Django 5.1.3 on 2024-11-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Leche", "Leche"),
                    ("Chocolate", "Chocolate"),
                    ("Fórmulas Infantiles", "Fórmulas Infantiles"),
                    ("Dulces", "Dulces"),
                    ("Galleta", "Galleta"),
                    ("Productos Extras", "Productos Extras"),
                ],
                max_length=255,
                verbose_name="Categoría del Producto",
            ),
        ),
    ]
