# Generated by Django 5.1.3 on 2024-12-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Leche", "Leche"),
                    ("Aceites", "Aceites"),
                    ("Chocolates", "Chocolates"),
                    ("Frijoles", "Frijoles"),
                    ("Higiene_Dental", "Higiene Dental"),
                    ("Fórmulas Infantiles", "Fórmulas Infantiles"),
                    ("Dulces", "Dulces"),
                    ("Galleta", "Galleta"),
                    ("Productos Extras", "Productos Extras"),
                ],
                max_length=255,
                verbose_name="Categoría del Producto",
            ),
        ),
    ]
